# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2023.6.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class DigitsEnum(int, Enum):
    """
    * `6` - 6 digits, widely compatible * `8` - 8 digits, not compatible with apps like Google Authenticator
    """

    """
    allowed enum values
    """
    NUMBER_6 = 6
    NUMBER_8 = 8

    @classmethod
    def from_json(cls, json_str: str) -> DigitsEnum:
        """Create an instance of DigitsEnum from a JSON string"""
        return DigitsEnum(json.loads(json_str))


