# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2023.6.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class DuoResponseEnum(str, Enum):
    """
    * `success` - Success * `waiting` - Waiting * `invalid` - Invalid
    """

    """
    allowed enum values
    """
    SUCCESS = 'success'
    WAITING = 'waiting'
    INVALID = 'invalid'

    @classmethod
    def from_json(cls, json_str: str) -> DuoResponseEnum:
        """Create an instance of DuoResponseEnum from a JSON string"""
        return DuoResponseEnum(json.loads(json_str))


