# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2023.6.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class FlowDesignationEnum(str, Enum):
    """
    * `authentication` - Authentication * `authorization` - Authorization * `invalidation` - Invalidation * `enrollment` - Enrollment * `unenrollment` - Unrenollment * `recovery` - Recovery * `stage_configuration` - Stage Configuration
    """

    """
    allowed enum values
    """
    AUTHENTICATION = 'authentication'
    AUTHORIZATION = 'authorization'
    INVALIDATION = 'invalidation'
    ENROLLMENT = 'enrollment'
    UNENROLLMENT = 'unenrollment'
    RECOVERY = 'recovery'
    STAGE_CONFIGURATION = 'stage_configuration'

    @classmethod
    def from_json(cls, json_str: str) -> FlowDesignationEnum:
        """Create an instance of FlowDesignationEnum from a JSON string"""
        return FlowDesignationEnum(json.loads(json_str))


