# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2023.6.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class IssuerModeEnum(str, Enum):
    """
    * `global` - Same identifier is used for all providers * `per_provider` - Each provider has a different issuer, based on the application slug.
    """

    """
    allowed enum values
    """
    GLOBAL = 'global'
    PER_PROVIDER = 'per_provider'

    @classmethod
    def from_json(cls, json_str: str) -> IssuerModeEnum:
        """Create an instance of IssuerModeEnum from a JSON string"""
        return IssuerModeEnum(json.loads(json_str))


