# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2023.6.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class NotificationTransportModeEnum(str, Enum):
    """
    * `local` - authentik inbuilt notifications * `webhook` - Generic Webhook * `webhook_slack` - Slack Webhook (Slack/Discord) * `email` - Email
    """

    """
    allowed enum values
    """
    LOCAL = 'local'
    WEBHOOK = 'webhook'
    WEBHOOK_SLACK = 'webhook_slack'
    EMAIL = 'email'

    @classmethod
    def from_json(cls, json_str: str) -> NotificationTransportModeEnum:
        """Create an instance of NotificationTransportModeEnum from a JSON string"""
        return NotificationTransportModeEnum(json.loads(json_str))


