# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2023.6.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictBool
from authentik.models.event_request import EventRequest

class NotificationRequest(BaseModel):
    """
    Notification Serializer
    """
    event: Optional[EventRequest] = None
    seen: Optional[StrictBool] = None
    __properties = ["event", "seen"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> NotificationRequest:
        """Create an instance of NotificationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of event
        if self.event:
            _dict['event'] = self.event.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> NotificationRequest:
        """Create an instance of NotificationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return NotificationRequest.parse_obj(obj)

        _obj = NotificationRequest.parse_obj({
            "event": EventRequest.from_dict(obj.get("event")) if obj.get("event") is not None else None,
            "seen": obj.get("seen")
        })
        return _obj


