# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2023.6.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ProviderEnum(str, Enum):
    """
    * `twilio` - Twilio * `generic` - Generic
    """

    """
    allowed enum values
    """
    TWILIO = 'twilio'
    GENERIC = 'generic'

    @classmethod
    def from_json(cls, json_str: str) -> ProviderEnum:
        """Create an instance of ProviderEnum from a JSON string"""
        return ProviderEnum(json.loads(json_str))


