# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2023.6.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ProxyMode(str, Enum):
    """
    * `proxy` - Proxy * `forward_single` - Forward Single * `forward_domain` - Forward Domain
    """

    """
    allowed enum values
    """
    PROXY = 'proxy'
    FORWARD_SINGLE = 'forward_single'
    FORWARD_DOMAIN = 'forward_domain'

    @classmethod
    def from_json(cls, json_str: str) -> ProxyMode:
        """Create an instance of ProxyMode from a JSON string"""
        return ProxyMode(json.loads(json_str))


