# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2023.6.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class SeverityEnum(str, Enum):
    """
    * `notice` - Notice * `warning` - Warning * `alert` - Alert
    """

    """
    allowed enum values
    """
    NOTICE = 'notice'
    WARNING = 'warning'
    ALERT = 'alert'

    @classmethod
    def from_json(cls, json_str: str) -> SeverityEnum:
        """Create an instance of SeverityEnum from a JSON string"""
        return SeverityEnum(json.loads(json_str))


