# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2023.6.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr
from authentik.models.used_by_action_enum import UsedByActionEnum

class UsedBy(BaseModel):
    """
    A list of all objects referencing the queried object
    """
    app: StrictStr = Field(...)
    model_name: StrictStr = Field(...)
    pk: StrictStr = Field(...)
    name: StrictStr = Field(...)
    action: UsedByActionEnum = Field(...)
    __properties = ["app", "model_name", "pk", "name", "action"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UsedBy:
        """Create an instance of UsedBy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UsedBy:
        """Create an instance of UsedBy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UsedBy.parse_obj(obj)

        _obj = UsedBy.parse_obj({
            "app": obj.get("app"),
            "model_name": obj.get("model_name"),
            "pk": obj.get("pk"),
            "name": obj.get("name"),
            "action": obj.get("action")
        })
        return _obj


