# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2023.6.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class UsedByActionEnum(str, Enum):
    """
    * `CASCADE` - CASCADE * `CASCADE_MANY` - CASCADE_MANY * `SET_NULL` - SET_NULL * `SET_DEFAULT` - SET_DEFAULT
    """

    """
    allowed enum values
    """
    CASCADE = 'CASCADE'
    CASCADE_MANY = 'CASCADE_MANY'
    SET_NULL = 'SET_NULL'
    SET_DEFAULT = 'SET_DEFAULT'

    @classmethod
    def from_json(cls, json_str: str) -> UsedByActionEnum:
        """Create an instance of UsedByActionEnum from a JSON string"""
        return UsedByActionEnum(json.loads(json_str))


