# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2023.6.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class UserCreationModeEnum(str, Enum):
    """
    * `never_create` - Never Create * `create_when_required` - Create When Required * `always_create` - Always Create
    """

    """
    allowed enum values
    """
    NEVER_CREATE = 'never_create'
    CREATE_WHEN_REQUIRED = 'create_when_required'
    ALWAYS_CREATE = 'always_create'

    @classmethod
    def from_json(cls, json_str: str) -> UserCreationModeEnum:
        """Create an instance of UserCreationModeEnum from a JSON string"""
        return UserCreationModeEnum(json.loads(json_str))


