# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2023.6.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class UserServiceAccountResponse(BaseModel):
    """
    UserServiceAccountResponse
    """
    username: StrictStr = Field(...)
    token: StrictStr = Field(...)
    user_uid: StrictStr = Field(...)
    user_pk: StrictInt = Field(...)
    group_pk: Optional[StrictStr] = None
    __properties = ["username", "token", "user_uid", "user_pk", "group_pk"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UserServiceAccountResponse:
        """Create an instance of UserServiceAccountResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UserServiceAccountResponse:
        """Create an instance of UserServiceAccountResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UserServiceAccountResponse.parse_obj(obj)

        _obj = UserServiceAccountResponse.parse_obj({
            "username": obj.get("username"),
            "token": obj.get("token"),
            "user_uid": obj.get("user_uid"),
            "user_pk": obj.get("user_pk"),
            "group_pk": obj.get("group_pk")
        })
        return _obj


